### ISSUE TITLE
style problem in admin panel widge

### ISSUE THREAD

**Issue by sphrlbd** [dzhuang/django-galleryfield#57]
hi, i have this style problem on admin panel 

![image](https://github.com/dzhuang/django-galleryfield/assets/59436254/11b0b5fd-3cfd-4e5f-97a4-ebb200644194)

**Comment by dzhuang** [comment]
Thanks for reporting. That's a [known issue](https://github.com/dzhuang/django-galleryfield/discussions/46) and I have no idea how to fix it. Also see discussion https://github.com/dzhuang/django-galleryfield/discussions/46 .

**Comment by sphrlbd** [comment]
It's fixed with changing the bootstrap version.
But i don't know how can I use two gallery field in one model
when I do that, all the files will be uploaded in one filed

**Comment by dzhuang** [comment]
>But i don't know how can I use two gallery field in one model
when I do that, all the files will be uploaded in one filed

Please open another issue or move to discussions.

**Comment by sphrlbd** [comment]
Ok thanks
